#ifndef __JEDECVENDORID_H__
#define __JEDECVENDORID_H__

enum JEDECVendorID {
    VENDOR_ID_ARM = 0x23b,
    VENDOR_ID_MICROCHIP = 0x029,
    VENDOR_ID_PHILIPS = 0x015,
    VENDOR_ID_XILINX = 0x049,
};

#endif
