#ifndef __JEDECVENDORID_H__
#define __JEDECVENDORID_H__

enum JEDECVendorID {
    VENDOR_ID_ARM 		= 0x23b,
    VENDOR_ID_ARM_TEST	= 0x787,
    VENDOR_ID_FREESCALE	= 0x00e,
    VENDOR_ID_MICROCHIP = 0x029,
    VENDOR_ID_PHILIPS	= 0x015,
    VENDOR_ID_STMICRO	= 0x020,
    VENDOR_ID_XILINX	= 0x049
};

#endif
