#ifndef __JTAGD_OPCODES_H__
#define __JTAGD_OPCODES_H__

enum jtagd_opcodes {
    JTAGD_OP_GET_NAME = 0x00,
    JTAGD_OP_GET_SERIAL = 0x01,
    JTAGD_OP_GET_USERID = 0x02,
    JTAGD_OP_GET_FREQ = 0x03,
    JTAGD_OP_SHIFT_DATA_WO = 0x06,
    JTAGD_OP_SHIFT_DATA = 0x07,
    JTAGD_OP_DUMMY_CLOCK = 0x08,
    JTAGD_OP_PERF_SHIFT = 0x09,
    //0x0a reserved for deleted opcode
    JTAGD_OP_PERF_DATA = 0x0b,
    JTAGD_OP_PERF_MODE = 0x0c,
    JTAGD_OP_PERF_DUMMY = 0x0d,
    JTAGD_OP_QUIT = 0x0e,
    JTAGD_OP_COMMIT = 0x0f,
    JTAGD_OP_SPLIT_SUPPORTED = 0x10,
    JTAGD_OP_SHIFT_DATA_WRITE_ONLY = 0x11,
    JTAGD_OP_SHIFT_DATA_READ_ONLY = 0x12,
    JTAGD_OP_DUMMY_CLOCK_DEFERRED = 0x13,
    JTAGD_OP_HAS_GPIO = 0x14,
    JTAGD_OP_GET_GPIO_PIN_COUNT = 0x15,
    JTAGD_OP_READ_GPIO_STATE = 0x16,
    JTAGD_OP_WRITE_GPIO_STATE = 0x17,
    JTAGD_OP_TLR = 0x18,
    JTAGD_OP_ENTER_SIR = 0x19,
    JTAGD_OP_LEAVE_E1IR = 0x1a,
    JTAGD_OP_ENTER_SDR = 0x1b,
    JTAGD_OP_LEAVE_E1DR = 0x1c,
    JTAGD_OP_RESET_IDLE = 0x1d,
};

#endif
