#ifndef __XILINXDEVICEID_H__
#define __XILINXDEVICEID_H__

enum XilinxDeviceID {
    XILINX_FAMILY_CR2_A = 0x36,
    XILINX_FAMILY_CR2_B = 0x37,
    XILINX_FAMILY_SPARTAN3A = 0x11,
    XILINX_FAMILY_SPARTAN6 = 0x20,
    XILINX_FAMILY_7SERIES = 0x1b,
    XILINX_FAMILY_ULTRASCALE = 0x1c,
    XILINX_FAMILY_USPLUS = 0x25,
};

#endif
